### ISSUE TITLE
trigger afterAddRule after createRuleFilters

### ISSUE THREAD

**Issue by mszoernyi** [mistic100/jQuery-QueryBuilder#110]
I'm writing an ember.js wrapper for the builder which depends on the triggers called to keep it in sync with ember.

When I'm passing a rule with a `data` key to `setRules` the [afterAddRule trigger](https://github.com/mistic100/jQuery-QueryBuilder/blob/a15746a35afe1136a18657cdb40b5fe577b1bcbc/src/core.js#L359) get an empty model passed which is then filled [one step later](https://github.com/mistic100/jQuery-QueryBuilder/blob/a15746a35afe1136a18657cdb40b5fe577b1bcbc/src/core.js#L361).

I'm not sure if I'm using the events wrongly but I would expect to get a proper rule passed not just one with an `id`.

**Comment by mistic100** [comment]
This won't change anything... the model is absolutely not filled "one step later" it's filled [here](https://github.com/mistic100/jQuery-QueryBuilder/blob/a15746a35afe1136a18657cdb40b5fe577b1bcbc/src/public.js#L224)

`setRules` behaves exactly like a "user", first add the rule (empty) then fill it.

**Comment by mszoernyi** [comment]
Ah ok. What are the best points then to observer to keep the builder model in sync with other frameworks?

Currently I'm observing `afterAddRule`, `_afterUpdateRuleFilter`, `_afterUpdateRuleOperator` and `afterAddGroup`

**Comment by mistic100** [comment]
I don't know, you have the list of events, that's it.

when [model.filter is set](https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/public.js#L224) it should call `afterUpdateRuleFilter` event and so on for operators, flags and value, **exactly like when the user manually add a rule and fill it**

---

you can also directly listen to data model events like https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/core.js#L207 (internal feature, undocumented, might change)

use the "afterInit" builder event to be sure the model is loaded

**Comment by mszoernyi** [comment]
Thanks this really helped. I even might use the model events instead.

**Comment by mszoernyi** [comment]
Would it be ok to move (these lines)[https://github.com/mistic100/jQuery-QueryBuilder/blob/a15746a35afe1136a18657cdb40b5fe577b1bcbc/src/public.js#L228-L230] up to line `201`? The `data` property is not used at any of these function but it would help to pass external references to keep the model in sync.

**Comment by mszoernyi** [comment]
Maybe it makes sense to move the `data` property up some lines and don't trigger `afterAddRule` when `setRules` is used. `afterAddGroup` is not triggered when using `setRules` only if I click the add-button. This way it's easy to differentiate and it would be less confusion.

**Comment by mistic100** [comment]
> Would it be ok to move these lines up to line 201?

Absolutely not [because](https://github.com/mistic100/jQuery-QueryBuilder/blob/a15746a35afe1136a18657cdb40b5fe577b1bcbc/src/public.js#L219)

> afterAddGroup is not triggered when using setRules

I really doubt this is true, there is not way the event is not [called](https://github.com/mistic100/jQuery-QueryBuilder/blob/a15746a35afe1136a18657cdb40b5fe577b1bcbc/src/core.js#L276) when àddGroup` is called from [here](https://github.com/mistic100/jQuery-QueryBuilder/blob/a15746a35afe1136a18657cdb40b5fe577b1bcbc/src/public.js#L207)

----

I will enhance `addRule` and `addGroup` method to accept more arguments

Then I will move [these instructions](https://github.com/mistic100/jQuery-QueryBuilder/blob/a15746a35afe1136a18657cdb40b5fe577b1bcbc/src/public.js#L224-L230) before [afterAddRule event](https://github.com/mistic100/jQuery-QueryBuilder/blob/a15746a35afe1136a18657cdb40b5fe577b1bcbc/src/core.js#L358) and [this instruction](https://github.com/mistic100/jQuery-QueryBuilder/blob/a15746a35afe1136a18657cdb40b5fe577b1bcbc/src/public.js#L197) before [afterAddGroup event](https://github.com/mistic100/jQuery-QueryBuilder/blob/a15746a35afe1136a18657cdb40b5fe577b1bcbc/src/core.js#L289)

**Comment by mistic100** [comment]
I didn't move everything because it would trigger "afterCreateRuleFilters" before "afterAddRule" and I don't want that

But I moved "data", and I added "data" for groups too, if you need it

**Comment by mszoernyi** [comment]
You are right, `afterAddGroup` is triggered, just not for the root group. Just didn't see the others between other debug logs.

Thanks for the super quick update, will try it right away.

**Comment by mszoernyi** [comment]
Thanks. Works really good this way.

**Comment by medokin** [comment]
@mszoernyi 

Is your Ember wrapper Open-Sourced?
