### ISSUE TITLE
Add setFilters(data) method

### ISSUE THREAD

**Issue by smailliwnosaj** [mistic100/jQuery-QueryBuilder#118]
I have an issue where I am saving the my Filter Rule collections to a database and recalling them later.  Available options in my ".rule-value-container select" fields can change over time.  So, when a User recalls a saved Filter Rule collection and the options are missing, the code errors out trying to assign a value to the select option which does not exist.

I needed a way to update the options.filters object on the fly when switching between saved Filter Rule collections.  Here is the solution I came up with.  I know you will come up with a more elegant solution if you ever decide to include it in a future version.

I updated query-builder.js to include the following (line 1158, just before QueryBuilder.prototype.setRules):

    /**
     * Set filters from object
     * @param data {object}
     */
    QueryBuilder.prototype.setFilters = function (data) {
        //console.log(data);
        //console.log(data.length);
        //console.log(this);

        if (!data || (data.length === 0 && !this.settings.allow_empty) || !data[0].id) {
            error('Incorrect data object passed');
        }

        //data = this.change('setFilters', data);

        var that = this;

        that.filters = data;
    };

In my code, I am execute the folllowing:

                        // Remove current filter
                        $("#mydiv").queryBuilder("reset");

                        // Load new Filter Definitions
                        $("#mydiv").queryBuilder("setFilters", filterDefinitions);  // new custom action

                        // Load selected filter data
                        $("#mydiv").queryBuilder("setRules", myFilterRuleCollection);

This solution works for me.  Let me know if you come up with a better one.

As always, thanks for your contributions,

Jason Williams

**Comment by smailliwnosaj** [comment]
As a result of updating the rule.filters collection on the fly, I uncovered an issue which has bothered me in a couple of different ways over this last month.  The rule.operator value can become stale.  To get around it, I updated a line in QueryBuilder.prototype.validateValueInternal to fetch the freshest value from the grid:

        var filter = rule.filter,
            //operator = rule.operator, 
            operator = rule.$el.find('.rule-operator-container [name$=_operator]').val(),
            validation = filter.validation || {},
            result = true,
            tmp;

This is obviously a hack solution.  The rule.operator value is called in many places through the code and validation is just one.  I don't use operators in the getRules() json.  Nor do I use the SQL or Mongo features.  So, this hack will work to keep my code functioning.

**Comment by smailliwnosaj** [comment]
As a result of updating the rule.filters collection on the fly, I uncovered an issue which has bothered me in a couple of different ways over this last two months. The rule.operator value can become stale. In my case, it was showing as operator of type "equal" when the rule was defined as "in" .  Doing a quick runtime check --  rule.$el.find('.rule-operator-container [name$=_operator]').val()  -- proves the ui being set to "in".  To get around it, I commented out the blocks in QueryBuilder.prototype.validateValueInternal which check if operator.multiple is false.

This is obviously a hack solution. The rule.operator value is called in many places through the code and validation is just one. I don't use operators in the getRules() json. Nor do I use the SQL or Mongo features. So, this hack will work to keep my code functioning.

**Comment by mistic100** [comment]
Honestly I don't understand your concern at all.

BTW I don't think it's a good idea to add this method. People might think that everything will be fine if they call the method without emptying the builder first, but it's not.

It's cleaner to just call `destroy` and re-init the builder again. Avoids a LOT of issues.

**Comment by smailliwnosaj** [comment]
Ahh.  Grr.  You're totally right.  I switched some things around and am, now, using 

$("#mydiv").queryBuilder("destroy");

instead of

$("#mydiv").queryBuilder("reset");

Problem solved.  You rock.

**Comment by cettinaraja** [comment]
Excuse me, i have a problem in this line:

$("#mydiv").queryBuilder("setFilters", filterDefinitions);  // new custom action

how can i create a filterDefinitions?

**Comment by mistic100** [comment]
exactly the same array of objects you pass when initializing the builder

**Comment by mistic100** [comment]
Also did you see that `setFilters` is now native in the last version ?
Do not use the patch of smailliwnosaj.

**Comment by cettinaraja** [comment]
Yes i know, but i have problem to pass it the filters array, occurred a javascript error, type mistmatch. Can you show me the complete code example? witch code i need to put inside [...]? 
Sorry for my english...
Thanx

**Comment by mistic100** [comment]
No.
YOU show what you are doing, not the other way around.

**Comment by cettinaraja** [comment]
Okay , i  added a function to the provided example to customize dinamically  the attribute list inside the selectbox . The code below :

var prova = {
  allow_empty: true,
  
  default_filter: 'state',
  
  optgroups: {
    core: {
      en: 'Core',
      fr: 'Coeur'
    }
  },

  plugins: {
    'bt-tooltip-errors': { delay: 100},
    'sortable': null,
    'filter-description': { mode: 'bootbox' },
    'bt-selectpicker': null,
    'unique-filter': null,
    'bt-checkbox': { color: 'primary' },
    'invert': null
  },

  filters: [
  /*
   * basic
   */
  {
    id: 'name',
    label: {
      en: 'Name',
      fr: 'Nom'
    },
    type: 'string',
    optgroup: 'core',
    default_value: 'Mistic',
    size: 30,
    unique: true
  },
  ]
};

$('#builder').on('getRuleFilterSelect.queryBuilder.filter', function(e, level) {
  $("#builder").queryBuilder("destroy");
  $('#builder').queryBuilder('setFilters', true, prova);
});

the error is:

Uncaught ConfigError: Missing filters list.

Can you help me to understand what is wrong?

Thanks

**Comment by mistic100** [comment]
it's called **setFilters** not **setConfig**, so use `prova.filters`.

I don't know what you are trying to do but overwriting the filters while the builder is initializing the rule dropdown will :
1. make your builder totally unuseable (it will reset itself)
2. probably crash your browser because of infinite loop

**Comment by cettinaraja** [comment]
My list of attributes is very large , so I want to create sub-lists that you can choose , like categories . OPTGROUP does not help me , because I would have too many attributes to show in a single selectbox. I thought to intercept the  AddRoule event to change the list of attributes shown...

**Comment by tahiralvi** [comment]
I have following  json which i want to update with old filters, but got error 

> TypeError: filters.forEach is not a function

`[{"id":"1260","label":"Have you experienced any symptoms or issues that concerned you since our last call?","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1261","label":" Is there anything you are concerned about today?","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1263","label":"Have you been taking your medications exactly as prescribed?","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1267","label":"Do you have any questions about your medications?","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1269","label":"Has there been any changes to your medication regimen (Newly Prescribed, Dosage/Frequency Change, or Discontinued)? ","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1277","label":"Since your last care coordination call, have you experinced any of the following ?","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1294","label":"Was the patient educated on the Call us First Program @ 844-248-2622?","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1295","label":"Were follow up interventions performed during this call?","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1296","label":"Please mark the type of interventions performed","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1297","label":"What actions were taken when following up with the Physician?","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1298","label":"Which actions were taken for Pharmacy Support?","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1299","label":"What Care Coordination was performed with the Home Health Agency?","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"1301","label":"Which actions were taken when following up with the ACO?","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false},{"id":"3360","label":"CARE COORDINATOR-YOU MUST NOTE CHANGES ON MEDICATION LIST","type":"string","input":null,"values":null,"operators":null,"validation":null,"plugin":null,"plugin_config":null,"value_separator":null,"default_value":null,"input_event":null,"size":0,"rows":0,"multiple":false,"placeholder":false}]`

I use Json Call and in success i write following code,
```
 $('#builder-import_export').queryBuilder("reset");
 $('#builder-import_export').queryBuilder('setFilters', true, data);
 $("#builder-import_export").queryBuilder("setRules", rules_basic);
```

> rules_basic is same as on initlize.

Anyone tell what is wrong

**Comment by mistic100** [comment]
Please use a correct markdown syntax, your code is not readable.

----

What browser are you using ? You probably need a polyfill https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Polyfill

**Do not respond to this issue** if your still have problems, this issue is closed.

**Comment by tahiralvi** [comment]
Here is the filters data which I try to update,

> https://www.dropbox.com/s/0ufisocvf7yugmh/NewFilterData.txt?dl=0

**Comment by abrarakazi** [comment]
I do understand that destroying the builder and reinitializing it with the new filter will solve the problem of updating the filter on the fly, but destroy method also destroys the already selected rules. 
I s there a way to only update filters without disturbing the previously created Rules ?
