### ISSUE TITLE
Input field width matches value

### ISSUE THREAD

**Issue by heportillo** [mistic100/jQuery-QueryBuilder#358]
I would like the input field widths to auto resize based on the value of the input. Any help on this would be appreciated!

**Comment by heportillo** [comment]
I would like the input field widths to auto resize based on the value of the input. Any help on this would be appreciated!

**Comment by mistic100** [comment]
Updated your messages to remove the guidelines -_-

----

```js
$('#builder').on('afterCreateRuleInput.queryBuilder', function(e, rule) {
   var theInput = rule.$el.find('.rule-value-container input');
   // your logic to resize theInput
});
```

**Comment by heportillo** [comment]
Thank you @mistic100. I passed along the information to our dev.

**Comment by lezhnev74** [comment]
Hi, guys! This issue is actually important for me too.
That would be awesome to find a way to make a value input take as much width as possible without going next line.

![](https://ftp.babystep.tv/screens/20170621_111733__z5qd7.jpg)

Do you have a hint on how to make it with jQuery?
@heportillo can you share your solution?
