### ISSUE TITLE
How can i restrict validation for the field's (not for the field group) ?

### ISSUE THREAD

**Issue by prasadraja07** [mistic100/jQuery-QueryBuilder#375]
Hi,

Thanks for  implementing such a wonderful plugin..

How can i stop validation only for the fields (not for the field group, it should remain same)

i tried to customize the plugin, but i am unable to sort the issue..

kindly suggest me, how can i stop validation on field ?

Your earliest reply will be highly appreciated

**Comment by mistic100** [comment]
I don't understand your need.

**Comment by prasadraja07** [comment]
Kindly find the attached image for your reference...

i hope this may help you...
![capture_1](https://cloud.githubusercontent.com/assets/2306153/19154655/0c7546f2-8bf9-11e6-9882-ea8a1f66cf00.PNG)

**Comment by mistic100** [comment]
what exactly is the difference between the two rules ?

**Comment by mistic100** [comment]
I think the `validationError.queryBuilder` [trigger](http://querybuilder.js.org/dev/events.html#triggers) is exactly what you need, see the example in the doc

Just call `e.preventDefault()` based on your logic

**BUT** please notice that even if the error is not displayed, the `getRules()` method will not work, because it was never designed to allow invalid data, and I don't think this will change.

**Comment by mistic100** [comment]
I cannot provide anything else than the example in the link above :

```js
$('#builder').on('validationError.queryBuilder', function(e, rule, error, value) {
  if (rule.filter.id == 'my_custom_filter') { // YOUR LOGIC
    e.preventDefault(); // CANCEL THE DISPLAY OF THE ERROR
  }
});
```
