### ISSUE TITLE
Validation fail on multiple number input

### ISSUE THREAD

**Issue by rpallares** [mistic100/jQuery-QueryBuilder#418]
## Description
If a filter of type number or double is defined, the "in" operator never validate the value if multiple values are defined

## Step to reproduce
- Create a filter as type equal 'double' or 'integer'
- Define a value separator (| in my case to not conflict with double commas)
- Launch the query builder
- add the filter and set "in" operator with value "3.5|3.2"
- Observe that the value is never validated

##Supposed cause
Function QueryBuilder.prototype.validateValueInternal only verify if there is multiple values on select and radio filters

**Comment by rpallares** [comment]
I'll try to implement that feature just by setting valueGetter and valueSetter and a validation.format regexp as workaroud.
But the best probably should be to re-write the QueryBuilder.prototype.validateValueInternal


Nice component in any cases :)

**Comment by mistic100** [comment]
What about "value_separator" option ? http://querybuilder.js.org/#filters

**Comment by mistic100** [comment]
You just cannot use number inputs with multiple values, is not even possible to write a pipe in modern browsers that support number inputs.

Your only solution is to use a text input and implement the validation callback yourself (because query builder does not support number validation in text inputs)

**Comment by mistic100** [comment]
Ok a really had an hard time understanding the problem (sorry for the previous deleted messages).

I'll investigate this, type: 'integer' with input: 'text' and a value_seperator should work

**Comment by mistic100** [comment]
After some research I guess you are not using Chrome or you are using a custom 'input' function, because in Chrome, because QueryBuilder uses `type="number"` you cannot even enter a pipe in the input.

So what I did is to add a new input type `number` which is the default for integer and double types, but if the user explicitly sets `type: 'integer`, input: 'text` it will uses a real test input.

Now the validation is still not working...

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/commit/4d6c44e83a98ce70ca2d3157934c2e2d8c707276#diff-5b0e3367cfabe5a0173e80753b827d6cR226

**Comment by rpallares** [comment]
OK, it's working perfectly :)
I had some difficulties to build the dev version due to the new jQuery.extendext dependency that is not yet documented.

Indeed, I don't use Chrome, I prefer Firefox which is open, although less well on some rare aspects. It don't prevent typing pipes into number inputs.

Thank you for your very quick fix, that feature will be very useful for my project.

**Comment by mistic100** [comment]
what do you mean "not documented" ? it's in dependency in the bower/package file and in the readme

**Comment by officiallysameer** [comment]
Hi Mistic,
The value separator works for strings but not for numbers (even when i specify the input type as text . I cannot get it to display the text type input.
Wonder what i am doing wrong. Here is a jFiddle example 
https://jsfiddle.net/z7dem1mg/

I tried to manually override this by replacing QueryBuilder.types[filter.type] in the following snippet with 
filter.input, i get the text input, but i get validation errors when i try to use value_separator
 ```
switch (QueryBuilder.types[filter.type]) {
                    case 'number':
                        h+= '<input class="form-control" type="number" name="' + name + '"';
                        if (validation.step !== undefined) h+= ' step="' + validation.step + '"';
                        if (validation.min !== undefined) h+= ' min="' + validation.min + '"';
                        if (validation.max !== undefined) h+= ' max="' + validation.max + '"';
                        if (filter.placeholder) h+= ' placeholder="' + filter.placeholder + '"';
                        if (filter.size) h+= ' size="' + filter.size + '"';
                        h+= '>';
                        break;

                    default:
                        h+= '<input class="form-control" type="text" name="' + name + '"';
                        if (filter.placeholder) h+= ' placeholder="' + filter.placeholder + '"';
                        if (filter.type === 'string' && validation.min !== undefined) h+= ' minlength="' + validation.min + '"';
                        if (filter.type === 'string' && validation.max !== undefined) h+= ' maxlength="' + validation.max + '"';
                        if (filter.size) h+= ' size="' + filter.size + '"';
                        h+= '>';
                }
```

**Comment by mistic100** [comment]
did you really build on dev branch and not on master ?

**Comment by officiallysameer** [comment]
i was pulling the contents from cdn earlier (jsdeliver), but wanted to look at  the code so copied the standalone from the dev branch to try manually override

**Comment by officiallysameer** [comment]
i think i have not built on dev branch.  Will try it now

**Comment by rpallares** [comment]
Oops, yes the jQuery.extendext is documented. I'm just tired on monday I guess.

**Comment by officiallysameer** [comment]
Hi Mistic,
Tried after rebuilding from dev. It worked.
Thanks man. You rock

**Comment by naveendb92** [comment]
@officiallysameer can you post a jsfiddle, support for multiple values for **IN** operator of type **integer**? I'm unable to get this done

**Comment by officiallysameer** [comment]
Hi Naveen,

I had built it from the code base. What problem are you facing?

On 9 Jan 2018 05:45, "Naveen D B" <notifications@github.com> wrote:

@officiallysameer <https://github.com/officiallysameer> can you post a
jsfiddle, support for multiple values for *IN* operator of type *integer*?
I'm unable to get this done

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mistic100/jQuery-QueryBuilder/issues/418#issuecomment-356186824>,
or mute the thread
