### ISSUE TITLE
Delete button

### ISSUE THREAD

**Issue by stanep** [mistic100/jQuery-QueryBuilder#434]
Hi , thank you for building this. I have a question I am trying to listen when someone click on "delete" and I have something like this

```coffeescript
$('#builder').on "afterDeleteRule.queryBuilder", (e, rule, error, value) ->
        # e.preventDefault()
        log('afterDeleteRule',e)
        log('afterDeleteRule',rule)
        log('afterDeleteRule',error)
        log('afterDeleteRule',value)
```

but looking into event.builder object I can not figure out which column users want to delete

**Comment by mistic100** [comment]
The doc clearly describe the paramaters of each event http://querybuilder.js.org/dev/events.html

And `afterDeleteRule` has none, because it's... after.

Use `beforeDeleteRule` if you want to know which one WILL BE deleted.

```js
$('#builder').on('beforeDeleteRule.queryBuilder', function(e, rule) {

});
```

----

please use correct markdown when posting code https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by stanep** [comment]
Thx :)
