### ISSUE TITLE
It seems a bug but not sure. 

### ISSUE THREAD

**Issue by lsh486love** [mistic100/jQuery-QueryBuilder#439]
First of all, I admire your solution "QueryBuilder". 

The logical expression doesn't seem to be well applied. 

Here is the picture that I applied as the following pic.

![mong](https://cloud.githubusercontent.com/assets/863747/23204841/699645ee-f92b-11e6-8abb-6e438aeb2c88.png)

There are 3 expression including a group. 
I understand (A, B) expressions are combined with ( C ) as "$or". 

But I don't understand which logical operator is omitted between ( A, B ). 
also, why does the expression C have "$and" operator? 

Is it possible that I can set an operator between ( A, B) ??

**Comment by mistic100** [comment]
What you don't understand is that the blue selector applies between the rules inside each group (yellow box)

So "OR" is applied between A, B and the subgroup, and "AND" is applied between C (alone).

This has been done like this because "nobody" knows that AND is evaluated before OR, so the builder provides no way to select the condition for each rule, instead you select the condition inside each group.

It's a good thing you use MongoDB because the generated query is exactly what the builder looks like, in SQL it woule be `A or B or (c)`  (the "AND" is loas here because C is alone)
