### ISSUE TITLE
When using filter with 'select' type, the operators 'in' and 'not in' do not allow multiple options to be selected

### ISSUE THREAD

**Issue by CrestApps** [mistic100/jQuery-QueryBuilder#474]
First of all, thank you for this great package!

When I use filter with `select` type, the operators `in` and `not in` do not allow multiple options to be selected. The menu should automatically allow multiple values when `in` or `not in` operations are used.

Here is the filters that I tried using. I selected, `State` filter, then tried to use the `in` operator then Select `NV` and `CA` it will not allow it.
```
[
   {
      "id":"3",
      "type":"string",
      "values":[

      ],
      "field":"BussinessName",
      "label":"Name",
      "input":"text"
   },
   {
      "id":"10",
      "type":"string",
      "values":[

      ],
      "field":"City",
      "label":"City",
      "input":"text"
   },
   {
      "id":"11",
      "type":"string",
      "values":[
         "AL",
         "WY"
      ],
      "field":"State",
      "label":"State",
      "input":"select"
   },
   {
      "id":"12",
      "type":"string",
      "values":[

      ],
      "field":"ZipCode",
      "label":"Zip Code",
      "input":"text"
   },
   {
      "id":"17",
      "type":"string",
      "values":[

      ],
      "field":"Phone1",
      "label":"Phone 1",
      "input":"text"
   },
   {
      "id":"19",
      "type":"string",
      "values":[

      ],
      "field":"Phone2",
      "label":"Phone 2",
      "input":"text"
   },
   {
      "id":"22",
      "type":"string",
      "values":[

      ],
      "field":"Email",
      "label":"Email",
      "input":"text"
   }
]
```

**Comment by mistic100** [comment]
I don't think it _should_, I try to have fewer automated things as possible because there will always be a need to de-automate it.

In this specific case you could just configure your filter with 
```js
multiple: true,
operators: ['in', 'not_in']
```

**Comment by CrestApps** [comment]
Thank you for a quick response. 
I want to use ['in', 'not_in','equal', ..... all others]  However, when I 'in' or 'not in' are selected, I want to alter the `select menu` that is holding the value to allow it to accept `multiple`

I think my best bet is to hook into the `afterUpdateRuleOperator.queryBuilder` as you suggested. 

However, how would I retrieve the selected value using this event to check if it is `in` or `not in`? This is what I started with but e.value is not returning the values and also not sure how to get the relevant menu to add `.attr('multiple','multiple')`

**Comment by mistic100** [comment]
Did you open the doc ? http://querybuilder.js.org/api/QueryBuilder.html#.event:afterUpdateRuleOperator
The first parameter (actually the second one because the first is the event itself) is the rule object with everything you need as detailed here http://querybuilder.js.org/#inside_the_box or here http://querybuilder.js.org/api/Rule.html

to get the selectbox :

```js
rule.$el.find('.rule-value-container select')
```

**Comment by mistic100** [comment]
Unfortunately this might not work because of this https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/data.js#L378

You must always set the `multiple` property of the filter to true in order to make it working.

**Comment by CrestApps** [comment]
Thank for your feedback. 
Using `equal` or `no equal` with multiple does not make sense :)

I think, until this restriction is lifted, I'll have to avoid using `in` and `not in`. I hope you consider improving this :)

Again thank you for this great package and your help today :)

**Comment by mistic100** [comment]
But you can combine it with the event handling to actually disable multiple values when equal is selected.

---

Sorry but this certainly won't be improved, I already thought about it and couldn't find a suitable solution.

**Comment by nikataus** [comment]
Hi Crest, I see this thread has been closed, but I have done something similar, so wanted to add my comments. I have in my form State and County filters, which I have preset respectively as single select and multiple select. Even built relation between the two, so when the User selects a state it will populate County control with respective data. Since I use multiselect for County I only use operators that relate to this type like in, not in... From what I understand you're trying to dynamically change the control type depending on what operator has been selected, and I'm sure you can use event handling like mistic suggests to change multiple values enable/disable.
