### ISSUE TITLE
how to Add selectize to rule filter? 

### ISSUE THREAD

**Issue by FirasKh** [mistic100/jQuery-QueryBuilder#590]
In query builder Documentation I saw how to add a selectize but i want to add the selectize to the rule_filter not for the value_filter so how can do it?

**Comment by mistic100** [comment]
You can try to create a plugin which will look like Bootstrap Selectpicker one's
https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/bt-selectpicker/plugin.js

The idead is to intercept the `afterCreateRuleFilters` event and initialize Selectize here.

**Comment by lestcape** [comment]
What is then the idea to have some incomplete examples?
It create the confusion to me. I think that i can used selectize as a replace of a rule with more than one option and this ofcurse is not already true. Is not possible that selectize load the data from the queryBuilder value properties of the rule and when this property change fill the data automatically in selectize?

Also the slider pluging can have a different validation than the original source if we change the rule on run time in the querybuilder. More correctly will be if the max and min values will be taking from the querybuilder and not from an external source and in addition to it.

As a resume, the examples are toys only. They are not something really useful.

**Comment by lestcape** [comment]
I see you add a RuleChange event (https://github.com/mistic100/jQuery-QueryBuilder/commit/e1887ad2650531ff3c3a0263442a8d7259251582), that can be used to fill the selectize on fly, when the rule change.

**Comment by mistic100** [comment]
The examples are here to show the basic usage of the library. I have absolutely not enough time in my life to make complete examples of every use case possible.

**Comment by lestcape** [comment]
@mistic100 thats fine... Just i think they are already fully integrate with QB while really are not. 

I can not capture **in the initialization** (if a selectizer plugin is selected for some rule) this signals:

- afterCreateRuleInput.queryBuilder
- afterUpdateRuleFilter.queryBuilder

Also not:
- afterInit.queryBuilder

 So, not way in that case to integrete the selectize. What signal will be the in this case?

**Comment by lestcape** [comment]
@mistic100 thanks for your QueryBuilder. If some one have an interest on this:

I finally reimplemented the examples, to be possible use it as part of the model and not as independent components. I use the php backend and i need then to use the things in a way they fill the query builder model or i can not use the backend then.

The Coordinate examples will then take the values from the filter configuration instead of an statically way. This is the values format of this example:
```
 var values = {
     'A': ['A', {'1': '1', '2': '2'}],
     'B': ['B', {'3': '3', '4': '4'}],
     'C': ['C', {'5': '5', '6': '6'}],
 };
```
Then this is the  coordinates configuration:
```
'coordinates': {
    "input": function(rule, name) {
        var $container = rule.$el.find('.rule-value-container');
        var values = rule.filter.values;
        $container.on('change', '[name='+ name +'_1]', function() {
            var h = '';
            var val = $(this).val();
            if (val in values) {
                var asValues = values[val][1];
                h += "<option value='-1'>-</option>";
                for (var key in asValues) {
                    h += "<option value='"+key+"'>"+asValues[key]+"</option>";
                }
            }
            $container.find('[name$=_2]')
                .html(h).toggle(!!h)
                .val('-1').trigger('change');
        });

        var h = "<select name='"+ name +"_1'>";
        h += "  <option value='-1'>-</option>";
        for (var key in values) {
            h += "  <option value='"+key+"'>"+values[key][0]+"</option>";
        }
        h += "</select>";
        h += "<select name='" + name +"_2' style='display:none;'></select>";
        return h;
    },
    "valueGetter": function(rule) {
        return rule.$el.find('.rule-value-container [name$=_1]').val()
          +'.'+ rule.$el.find('.rule-value-container [name$=_2]').val();
    },
    "valueSetter": function(rule, value) {
        if (rule.operator.nb_inputs > 0) {
            var val = value.split('.');
            rule.$el.find('.rule-value-container [name$=_1]').val(val[0]).trigger('change');
            rule.$el.find('.rule-value-container [name$=_2]').val(val[1]).trigger('change');
        }
    },
 },
```

For selectize plugin i move the "_fix"_ to the onInitialize event and i take the values from the filter in this format (please not in my case the imput is a select, not a normal input, like in the example):
```
"id": "category", "label": "Selectize", "type": "integer", "input":  "select",
"values": [1: "Books", 2: "Movies", 3: "Music", 4: "Tools", 5: "Goodies", 6: "Clothes"),
"operators": ['equal', 'not_equal']
```
Then i also implement the setter and getter for that plugin.
```
'selectize': {
    "plugin_config": {
        "valueField": 'id',
        "labelField": 'name',
        "searchField": 'name',
        "sortField": 'name',
        "create": true,
        "maxItems": 1,
        "plugins": ['remove_button'],
        "onInitialize": function() {
          var elem = $(this.$input[0]);
          if(elem.length) {
              elem.closest('.rule-value-container').css('min-width', '200px')
                 .find('.selectize-control').removeClass('form-control');
          }
      },
    },
    "valueSetter": function(rule, value) {
        rule.$el.find('.rule-value-container select')[0].selectize.setValue(value);
    },
    "valueGetter": function(rule) {
        return rule.$el.find('.rule-value-container select')[0].selectize.getValue();
    },
},
```

Finally for the slider example, after initialized or set a filter i fill the `plugin_config`with the `filter_config` values (min, max are equals) and i set the default value property to the min.

All that give me the chance to not need to create a complete alternative way to control  the query builder with special cases, with is really nice, as i don' t need to do any specially thing to used the php backend.

Regards.

**Comment by lestcape** [comment]
I try to implemented a selectize plugin from rules filters. Really i have a modify version of selectize, because i don't want to use the backspace to delete the current value and i use a plugin called typing_mode on selectize to avoid that some time ago (https://github.com/selectize/selectize.js/issues/670).

I have actually a problem with this lines:
https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/core.js#L204
https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/core.js#L210

Because when the selectize drop-down is displayed i blank the selectize value and ofcourse the filter or the operator can not be find in this case. I wonder, if is possible removed the exception in this case (on master) or will brings some conflict? The way to solve this is probably pass the extra argument `options.allow_invalid` to the `getOperatorByType` and `getFilterById` functions. This can be done @mistic100?

**This is my plugin:**
```
    /**
     * @class Selectize
     * @memberof module:plugins
     * @description Applies Selectize on filters and operators combo-boxes.
     * @throws MissingLibraryError
     */
    var QueryBuilder = $.fn.queryBuilder;
    QueryBuilder.define('selectize', function(options) {
        if (!$.fn.selectize || !$.fn.selectize.constructor) {
            throw('MissingLibrary: selectize component is required to use "selectize" plugin. Get it here: https://github.com/selectize/selectize.js');
        }

        var Selectors = QueryBuilder.constructor.selectors;

        // init selectize
        this.on('afterCreateRuleFilters', function(e, rule) {
            rule.$el.find(Selectors.rule_filter).removeClass('form-control').selectize(options);
        });

        this.on('afterCreateRuleOperators', function(e, rule) {
            rule.$el.find(Selectors.rule_operator).removeClass('form-control').selectize(options);
        });

        // update selectize on change
        this.on('afterUpdateRuleFilter', function(e, rule) {
            //rule.$el.find(Selectors.rule_filter).selectize('render');
            var newValue = rule.filter ? rule.filter.id : '-1';
            if (newValue && (newValue !== '-1')) {
                var ss = rule.$el.find('.rule-filter-container select')[0].selectize;
                if(ss.getValue() !== newValue) {
                    ss.setValue(newValue);
                }
            }
        });

        this.on('afterUpdateRuleOperator', function(e, rule) {
            //rule.$el.find(Selectors.rule_operator).selectize('render');
            if (rule.operator) {
                var ss = rule.$el.find('.rule-operator-container select')[0].selectize;
                if(ss.getValue() !== rule.operator.type) {
                    ss.setValue(rule.operator.type);
                }
            }
        });

        this.on('beforeDeleteRule', function(e, rule) {
            var ssf = rule.$el.find('.rule-filter-container select')[0].selectize;
            var ssp = rule.$el.find('.rule-operator-container select')[0].selectize;
            ssf.destroy();
            ssp.destroy();
        });
    }, {
        "valueField": 'id',
        "labelField": 'name',
        "searchField": 'name',
        "sortField": 'name',
        "create": false,
        "maxItems": 1,
        "initUnselected": false,
        "usePlaceholder": false,
        "plugins": ['typing_mode', 'remove_button'],
        "onInitialize": function() {
            var elem = $(this.$input[0]);
            if(elem.length) {
                elem.closest('.rule-operator-container').css('min-width', '100px')
                    .find('.selectize-control').removeClass('form-control');
                elem.closest('.rule-filter-container').css('min-width', '200px')
                    .find('.selectize-control').removeClass('form-control');
            }
        },
    });
```

**Comment by lestcape** [comment]
A change on this lines also solved the issue:
`if (id == '-1') {` by this one `if (id === '-1') || (id === '') {` https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/data.js#L324
`if (type == '-1') {` by this one `if ((type === '-1') || (type === '')) {` https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/data.js#L348
