### ISSUE TITLE
setRulesFromSQL problem with numbers at start of table name

### ISSUE THREAD

**Issue by StephenPOCT** [mistic100/jQuery-QueryBuilder#594]
I have the following SQL expression
```javascript
"99Table1.State = 'hhjhjhjhjhjhhj'"
```
I am attempting to execute it as follows:
```javascript
var filter = "99Table1.State = 'hhjhjhjhjhjhhj'";
$('#element').queryBuilder('setRulesFromSQL', filter);
```
I receive the following error:
```
angular.js:119 UndefinedFilterError: Undefined filter "99"
    at Object.k.error ([removed]/query-builder.standalone.min.js:8:8162)
    at g.getFilterById ([removed]/query-builder.standalone.min.js:7:28827)
    at [removed]/query-builder.standalone.min.js:7:23894
```

This problem seems to only present itself when the table name starts with a number. Any ideas on how to work around this?

**Comment by mistic100** [comment]
This is how the parser is coded https://github.com/mistic100/sql-parser/blob/master/src/lexer.coffee#L171
Because it so mush easier to parse litterals when they do not start with a number.

Historically, SQL names weren't allowed to start with a number for the same reason. Although it is now supported by major SQL engines.

**I cannot change the parser, it too much complicated.** If you cannot rename your tables (which I advise). You will have to replace the offending name before consuming the request in QueryBuilder.

**Comment by mistic100** [comment]
More info on why and how it is not a good idea to have your columns starting by a number :
https://stackoverflow.com/questions/15917064/table-or-column-name-cannot-start-with-numeric
https://stackoverflow.com/questions/6114193/column-name-beginning-with-a-number

**Comment by StephenPOCT** [comment]
It seems that using  square brackets also doesn't work in the parser

```Javascript
var filter = "[99Table1].[State] = 'hhjhjhjhjhjhhj'";
```

Is it possible to perhaps allow this scenario to work?

**Comment by StephenPOCT** [comment]
We have solved this problem internally.

Please feel free to contact us directly for the solution

**Comment by RiteshS21** [comment]
> We have solved this problem internally.
> 
> Please feel free to contact us directly for the solution

@StephenPOCT  Could you please help me how to solve the same issue?
