### ISSUE TITLE
Seeing multiple afterUpdateRuleValue.queryBuilder events when calling setRules

### ISSUE THREAD

**Issue by taylor-rolison** [mistic100/jQuery-QueryBuilder#630]
Hello,

I would like to preface this by saying a am extremely new to javascript so I apologize if I am just misunderstanding how this works.  

I want to do some addition processing when the user sets the value for specific filters. To do this I am using the _afterUpdateRuleValue.queryBuilder_ callback and that works great. The problem occurs when I use _setRules_ method to load saved rules. When I call the method I am seeing **5** _afterUpdateRuleValue.queryBuilder_ callbacks for each rule. I have recreated behavior [here](https://jsfiddle.net/rr4t7x03/). Is this expected behavior? I tried to dig into the events but they all seem like duplicates except for timestamp.

**Comment by mistic100** [comment]
I admit there too much triggers, there should be 3 instead of 5. But it is expected because the rule is initialized in cascade : filter > operator > value. And each steps goes to the end.

If you have to handle "setRules" differently than a user input you must track it yourself with a flag you set before calling setRules and reset just after.

**Comment by taylor-rolison** [comment]
Oh that makes sense. Okay, I will try the flag technique to get around this. Thank you for the help!
