### ISSUE TITLE
Get Mongo Code from JSON

### ISSUE THREAD

**Issue by ShwetaQuovantis** [mistic100/jQuery-QueryBuilder#67]
Hi mistic100,

I am using MONGODB as database, Is there a chance to add functionality in order to get valid Mongo where clause out of json string(just like its there for SQL)?

Thanks

**Comment by risingsunomi** [comment]
Hi mistic100, 

Just added some hack to make mongodb search queries make separate parts using the same rule for text values entered separated by a comma in the query-builder-mongodb-support.js code. I want to share it and was wondering how I would do that? Should I post my code changes here? I also wanted to make it so that string type filters can also have a textarea as an input but don't know how to go around that without breaking things in query-builder.js. If you can give me some direction that would be great.

Thanks

**Comment by mistic100** [comment]
1. I don't understand at all... you can fork and make a pull request if you want

2. You will have to modify the method which create the input, if you keep attributes you won't break anything

**Comment by risingsunomi** [comment]
Thanks I will looking into modifying the method that creates the input and this is what I was talking about. When you enter in values separated by a command the querybuilder addon I made makes different statements within the mongodb string like when you add rules

![Image of modification]
(http://nosudo.co/code/src/1420270240834.png)

**Comment by risingsunomi** [comment]
Forked and added what I did here https://github.com/risingsunomi/jQuery-QueryBuilder-Modified/blob/master/src/query-builder-mongodb-support.js

**Comment by mistic100** [comment]
ok so it's specific usage, I won't add it in the core
