### ISSUE TITLE
How to always use OR operator between groups 

### ISSUE THREAD

**Issue by Pryanic** [mistic100/jQuery-QueryBuilder#689]
How to always use OR operator between groups and AND between rules?

**Comment by mistic100** [comment]
A condition is not applied _between_ items but _inside_ a group, and a group can contain both groups and rules.
See https://github.com/mistic100/jQuery-QueryBuilder/issues/439

So in order to get the behavior you want, we should be able to restrict which groups can contain only groups or only rules, configuration hell !

The only thing you can do is initializing the builder and use the flags described here http://querybuilder.js.org/#method-setRules

```js
$('#builder').queryBuilder('setRules', {
  condition: 'OR',
  flags: {condition_readonly: true, no_add_rule: true},
  rules: [
    {
      condition: 'AND',
      flags: {condition_readonly: true, no_add_group: true},
      rules: []
    }
  ]
});
```

**Comment by Pryanic** [comment]
I tried to do and got 
query-builder.standalone.min.js:7 Uncaught Error: Incorrect data object passed
    at Object.h.error (query-builder.standalone.min.js:7)
    at g.setRules (query-builder.standalone.min.js:6)
    at r.fn.init.$.fn.queryBuilder (query-builder.standalone.min.js:7)

**Comment by mistic100** [comment]
add `rules: []` to the object passed to "setRules"

When posting an error, please use the unminified version of the code, with the minified code it's impossible to find where the error is thrown.

**Comment by Pryanic** [comment]
Ty it's helped me. 
But how I can remove button add group in subgroups 
![image](https://user-images.githubusercontent.com/13783593/39581454-46fc784e-4ef4-11e8-84a5-70d3d4cc7077.png)
?

**Comment by mistic100** [comment]
This is a bug, the `default_group_flags` should be applied.

**Comment by saurabhsingh121** [comment]
I was searching for the way to remove the 'add group' button from sub groups. I landed up here. Please tell me how to do it?
