### ISSUE TITLE
Tooltip error

### ISSUE THREAD

**Issue by mistic100** [mistic100/jQuery-QueryBuilder#71]
The library assumes that $.tooltip is Bootstrap one, at it fails if one use jQuery UI instead.

**Comment by lestcape** [comment]
This was resolved? I compiled jquery-ui without tooltips and also without sliders to not conflict with jQuery-QueryBuilder (version 2.5.2), because also the jquery-ui sliders enter in conflicts with the bootstrap-sliders.

Unfortunately I want to use this plugin in combination with [pivottable.js](https://pivottable.js.org) and pivottable.js needs jquery-ui to work. Situations like that are really dramatically, because both are pretty useful tools and when both are used in combination you can cover a fully functional report tool.

Actually I'm making an evaluation to decide if i can drop the jquery-ui dependency of pivottable.js in favour of the interact.js library, to resolve the conflict in a better way, but this is a lot of work, because i will need to change the pivottable.js and I'm also not the author of this library.

I know that this is not really a fault of  jQuery-QueryBuilder, but a workaround to work with both implementations (bootstrap and jquery-ui widgets) could help to resolve similar situations of conflicts.

**Comment by mistic100** [comment]
The tooltip is only used in "bt-tooltip-errors", it won't be so much work to create your own plugin using jQueryUI.
https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/bt-tooltip-errors/plugin.js
