### ISSUE TITLE
Issue creating custom operators

### ISSUE THREAD

**Issue by LorenzoFranciscoPena** [mistic100/jQuery-QueryBuilder#750]
I´m trying to create a custom operator for selecting next week and I think I`m pretty close
The idea is to send just "next_week" to the backend and adapt the query there.
This works perfect, it gives me the results I want but after searching, my filter disappears, so I have to add it again every time I want to make search or try a new combination of filters.
I tried changing the sqlOperators but I only got my filter changed, por example
from
DATE -> next week 
to
DATE -> equals --> next we

This is a part of my code:
```
$('#advancedFilter').queryBuilder({
	allow_empty: true, 
	rules: [],
	operators: $.fn.queryBuilder.constructor.DEFAULTS.operators.concat([
		{type: 'next_week', nb_inputs: 0, multiple: false, apply_to: ['datetime']},
		]),
	lang: {
		operators: {
			next_week: 'next week',
			}
		},	
	sqlOperators: {
		next_week: {op: 'next week' },
		},	
	filters: [
		type: 'datetime',
		validation: {
		format: 'YYYY/MM/DD'
			},
		plugin: 'datepicker',
		plugin_config: {
		dateFormat: 'yy/mm/dd',
		autoclose: true
			},
		operators: ['next_week']
		},
	]
});
```

**Comment by mistic100** [comment]
Please create on online demo (jsfiddle or other)

**Comment by skoskie** [comment]
@mistic100 @LorenzoFranciscoPena ... I might be 7 years out of date here, but I created a plugin for handling relative dates since I needed it for my project and such a plugin did not appear to exist. ... https://github.com/skoskie/jQuery-QueryBuilder-Relative-Date-Plugin

I've tested it in my own very large project and it is working without any issue. Still, contributions and feedback are welcome.
