### ISSUE TITLE
Configuring Selectize from php

### ISSUE THREAD

**Issue by nWidart** [mistic100/jQuery-QueryBuilder#76]
Hi,

First of all, thank for building this great tool! :smiley: 

I'm trying to use `selectize` plugin to make all my dropdowns as selectize instances. One important detail is that I make the filters array from a php script, which I return to the view using `json_encode` and place inside the `filters` key.

Something like the following:

``` javascript
$('#builder').queryBuilder({
    sortable: true,

    icons: {
        add_group: 'fa fa-plus',
        add_rule: 'fa fa-plus',
        remove_group: 'fa fa-times',
        remove_rule: 'fa fa-times',
        sort: 'fa fa-sort'
    },

    filters: <?php echo $filters; ?>
});

```

Only I'm wondering how to use selectize with this kind of structure. Since I can't make that closure you have in the [example](http://mistic100.github.io/jQuery-QueryBuilder/demo-widgets.html) `onInitialize`, where you loop over every item to add it to selectize.
I do have the data in the `values:` key though, like a classic dropdown without plugins.

Thank you!

**Comment by mistic100** [comment]
use the `plugin_options` QueryBuilder option and `options` Selectize option
https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md#data_searching

**Comment by mistic100** [comment]
and also you certainly won't be able to just use json_encode, one day or another you will want to use the callbacks and then you will have to replace your "echo $filter" by a more complex PHP script

I did that in JSP, it's pretty simple

**Comment by nWidart** [comment]
Oh right, thank you for the quick answer.

I'm now getting the following error:

```
TypeError: c is undefined selectize.min.js:2:5666
TypeError: f[c.plugin] is not a function
```

My the filter section responsible for the drop down as follows:
![screen shot 2015-01-14 at 11 39 51 am](https://cloud.githubusercontent.com/assets/882397/5737562/6afa9c62-9be2-11e4-916b-dbf01afc9154.png)

At first look, it's looking correct, but I'm certainly missing something stupid.

Thank your,

**Comment by nWidart** [comment]
Using the non minified version I get:

```
TypeError: MicroPlugin is undefined selectize.js:542:1
TypeError: $inputs[filter.plugin] is not a function
```

**Comment by mistic100** [comment]
perhaps you should read the readme of selectize and see that it a require a few dependencies
or use the standalone version https://github.com/brianreavis/selectize.js#files

--

are we done with the QueryBuilder part ?

**Comment by nWidart** [comment]
Alright my bad, I didn't include selectize's standalone build.

Input field is empty though, without any js errors.

**Comment by nWidart** [comment]
Sure.. sorry for the trouble then. Carry on.

**Comment by nWidart** [comment]
Tried to customize an example in selectize folder, and using the `options` key works perfectly there. It's only in the builder script where they aren't used.

I even tried to copy the generated filter string, pasted the values inside the selectize demo page, and everything works as expected...

**Comment by mistic100** [comment]
any chance to have a live version ?

**Comment by nWidart** [comment]
Hm can't publish this app, since it's under NDA.

**Comment by mistic100** [comment]
and I can't help without a POC

**Comment by nWidart** [comment]
I'll make a quick demo outside the main application.

**Comment by nWidart** [comment]
Here it is: http://www.maatwebsite.nl/demo-builder/
The 'Country' option.

**Comment by mistic100** [comment]
step #1: never trust what I say and always read the doc
http://mistic100.github.io/jQuery-QueryBuilder/#filters

it's `plugin_config` not `plugin_options`

:-)

**Comment by nWidart** [comment]
Oh, indeed.

I've updated the demo with the updated namings. Now when opening the selection of countries, on first opening, the dropdown is empty. But after selecting at least one country, it works as expected.

**Comment by mistic100** [comment]
The drop-down is not empty, it has a null width
And that because elements in querybuilder are inline
And that why my demo has a piece of code to force the min-width (can also be done in pure css)

**Comment by nWidart** [comment]
Right, thanks. :)

Why is it duplicating content though ? Again, in Selectize on its own, no duplication.
In a clean selectize demo page:

![screen shot 2015-01-15 at 7 59 06 am](https://cloud.githubusercontent.com/assets/882397/5753642/7fb5f8f4-9c8c-11e4-95d3-d84f17f17388.png)

In the query-builder:

![screen shot 2015-01-15 at 7 59 17 am](https://cloud.githubusercontent.com/assets/882397/5753643/8334ab6a-9c8c-11e4-8e43-0a4625e7fcf7.png)

**Comment by mistic100** [comment]
Elements are duplicated because they are duplicated in your data source....
--
could you please read the whole widget example ?
http://mistic100.github.io/jQuery-QueryBuilder/demo-widgets.html
you **need** the `onAfterSetValue` callback to fill the Selectize

**Comment by nWidart** [comment]
As said before, they aren't duplicated in the source...

```
{
                                "id": "1",
                                "name": "Afghanistan"
                            },
                            {
                                "id": "2",
                                "name": "Aland Islands"
                            },
                            {
                                "id": "3",
                                "name": "Albania"
                            },
                            {
                                "id": "4",
                                "name": "Algeria"
                            },
```
Since it's working in the basic example with the **exact** same data.

**Comment by jsdev** [comment]
@mistic100

loving querybuilder.

the demo site somepoint recently stopped working with selectize http://mistic100.github.io/jQuery-QueryBuilder/demo.html

**Comment by pschwien** [comment]
@mistic100 <https://github.com/mistic100>

The querybuilder looks great and it would be a great feature to have on a
page I am working on. I was looking into the demos and everything. Since I
am not a web-developer, I have difficulties getting a minimal example going
and since the demos don’t seem to use the query-builder.min.js directly I
could so far not get it to run. I would think all I need to put in my html
file are links to *.css and *.min.js files in the header.



Here is what I have:

Using the standalone version I think the only things I need in the html
header are:

<link rel="stylesheet" href="
https://raw.githubusercontent.com/mistic100/jQuery-QueryBuilder/master/dist/css/query-builder.default.min.css
">

<link rel="stylesheet" href="
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script src="
https://raw.githubusercontent.com/mistic100/jQuery-QueryBuilder/master/dist/js/query-builder.standalone.min.js
"></script>



My code in the body looks like this (taken from example page):



<div id="builder"></div>

<script>

var rules_basic = {

  condition: 'AND',

  rules: [{

    id: 'price',

    operator: 'less',

    value: 10.25

  }, {

    condition: 'OR',

    rules: [{

      id: 'category',

      operator: 'equal',

      value: 2

    }, {

      id: 'category',

      operator: 'equal',

      value: 1

    }]

  }]

};



   $('#builder').queryBuilder({filters: [{

    id: 'name',

    label: 'Name',

    type: 'string'

  }, {

    id: 'category',

    label: 'Category',

    type: 'integer',

    input: 'select',

    values: {

      1: 'Books',

      2: 'Movies',

      3: 'Music',

      4: 'Tools',

      5: 'Goodies',

      6: 'Clothes'

    },

    operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']

  }, {

    id: 'in_stock',

    label: 'In stock',

    type: 'integer',

    input: 'radio',

    values: {

      1: 'Yes',

      0: 'No'

    },

    operators: ['equal']

  }, {

    id: 'price',

    label: 'Price',

    type: 'double',

    validation: {

      min: 0,

      step: 0.01

    }

  }, {

    id: 'id',

    label: 'Identifier',

    type: 'string',

    placeholder: '____-____-____',

    operators: ['equal', 'not_equal'],

    validation: {

      format: /^.{4}-.{4}-.{4}$/

    }

  }],



  rules: rules_basic

});

</script>



Unfortunately nothing is showing up, and I was wondering if you could help
me by pointing out the misconceptions that I seem to have.



What would be really helpful to have on the project page would be a working
minimal example including all dependency files downloadable as a zip file
which I can just unzip into my /var/www/ folder that would create a working
example on my webserver.



Thank you so much,

Patrick





*From:* Anthony Delorie [mailto:notifications@github.com]
*Sent:* Thursday, July 30, 2015 11:24 PM
*To:* mistic100/jQuery-QueryBuilder
*Subject:* Re: [jQuery-QueryBuilder] Configuring Selectize from php (#76)



@mistic100 <https://github.com/mistic100>

loving querybuilder.

the demo site somepoint recently stopped working with selectize
http://mistic100.github.io/jQuery-QueryBuilder/demo.html

—
Reply to this email directly or view it on GitHub
<https://github.com/mistic100/jQuery-QueryBuilder/issues/76#issuecomment-126579451>
.

**Comment by mistic100** [comment]
Create a new issue, this one is closed and is not related

also please use Markdown syntax when posting code (click on "Markdown supported" above the form)
