### ISSUE TITLE
A question on allow_empty

### ISSUE THREAD

**Issue by biligee** [mistic100/jQuery-QueryBuilder#90]
How "allow_empty" is works? I set is as "true" and left some fields empty and inputted an query in one or two fields only. I was expecting to output  empty fields as empty with queries only that I inputted. However, it is giving errors.  
Similarly, how do I set some fields as "mandatory" that will not take empty values, and some fields can have empty values?

**Comment by mistic100** [comment]
Did you read the doc ?
http://mistic100.github.io/jQuery-QueryBuilder/#usage

By design, everything must be completed

**Comment by biligee** [comment]
allow_empty says: No error will be thrown is the builder is "entirely" empty. I need something like "partially" empty not "entirely".

**Comment by mistic100** [comment]
ok so you understood the purpose of this option

as I said "by design" you can't have an incomplete rules
if you need to allow empty values and "is null" or "is empty" do not suit you, you might define new specific operators

understand me, the purpose is to always output a coherent JSON, if the rule uses an operator expecting a value, there is a value, if the rule uses an operator no expecting a value, there is no value (`null` actually)
