### ISSUE TITLE
Custom Plugin requires an edit of the Rule's structure in order to work

### ISSUE THREAD

**Issue by VanHiro** [mistic100/jQuery-QueryBuilder#931]
## The Problem
I created a custom plugin but to make it work I need to edit the Rule's structure from the file querybuilder-standalone itself.
The plugin adds a button like the one from the plugin not-group inside each rule. The function of this plugin is to transform an input like this 'field = "value"' into this 'UPPER( field ) = "VALUE"'. The problem with this solution is that, in order to reuse this query (get/set SQL), I need to modify the structure of the Rule itself in the query-builder. 
_You can find this question also in stackoverflow:_
https://stackoverflow.com/questions/69646450/jquery-querybuilder-editing-the-rules-structure-in-the-file-query-builder-stan

## The Code
The edits I would need to make are the following:
_You can find the original code at line 2242 of the file query-builder.standalone.js_
```
if (model.filter) {
    model.filter.to_upper = item.to_upper; /* <---This is the line I added myself */
    model.operator = self.getOperatorByType(item.operator, !options.allow_invalid);
    if (!model.operator) {
       model.operator = self.getOperators(model.filter)[0];
    }
}
```

And this:
_Original code between line 6215 and 6232_
```
var id = self.getSQLFieldID(field, value);
//The following line is the code I need
var to_upper = data.to_upper;
/**
* Modifies the rule generated from the SQL expression
* @event changer:sqlToRule
* @memberof module:plugins.SqlSupport
* @param {object} rule
* @param {object} AST
* @returns {object}
*/
var rule = self.change('sqlToRule', {
   id: id,
   field: field,
   operator: opVal.op,
   value: opVal.val,
   //The following line us the code I need
   to_upper: to_upper
}, data);
```

>'to_upper' is a property I set to false by default and to true when its related button it's clicked.

## The Question
How could I do this without adding these code to query-builder itself?

**Comment by mistic100** [comment]
Please show the entirety of your plugin.

Sent from MailDroid

-----Original Message-----
From: VanHiro ***@***.***>
To: mistic100/jQuery-QueryBuilder ***@***.***>
Cc: Subscribed ***@***.***>
Sent: jeu., 21 oct. 2021 8:10
Subject: [mistic100/jQuery-QueryBuilder] I created a custom plugin but it only works if I edit the Rule's structure from the file querybuilder-standalone itself (Issue #931)

## The Problem
The plugin I've created adds a button like the one from the plugin not-group inside each rule. The function of this plugin is to transform an input like this 'field = "value"' into this 'UPPER( field ) = "VALUE"'. The problem with this solution is that, in order to reuse this query (get/set SQL), I need to modify the structure of the Rule itself in the query-builder. 

## The Code
The edits I would need to make are the following:
_You can find the original code at line 2242 of the file query-builder.standalone.js_
```
if (model.filter) {
    model.filter.to_upper = item.to_upper; /* <---This is the line I added myself */
    model.operator = self.getOperatorByType(item.operator, !options.allow_invalid);
    if (!model.operator) {
       model.operator = self.getOperators(model.filter)[0];
    }
}
```

And this:
_Original code between line 6215 and 6232_
```
var id = self.getSQLFieldID(field, value);
//The following line is the code I need
var to_upper = data.to_upper;
/**
* Modifies the rule generated from the SQL expression
* @event changer:sqlToRule
* @memberof module:plugins.SqlSupport
* @param {object} rule
* @param {object} AST
* @returns {object}
*/
var rule = self.change('sqlToRule', {
   id: id,
   field: field,
   operator: opVal.op,
   value: opVal.val,
   //The following line us the code I need
   to_upper: to_upper
}, data);
```

>'to_upper' is a property I set to false by default and to true when its related button it's clicked.

## The Question
How could I do this without adding these code to query-builder itself?

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/mistic100/jQuery-QueryBuilder/issues/931
